/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/activities': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['list_activities']
    put?: never
    post: operations['create_activity']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/activities/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch: operations['update_activity']
    trace?: never
  }
  '/api/activities/{id}/unvoid': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['unvoid_activity']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/activities/{id}/void': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['void_activity']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/callback': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['callback']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Start the login. Dev mode signs the dev user in directly. */
    get: operations['login']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['logout']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/day': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['day']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/days': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['days']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/foods': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['list_foods']
    put?: never
    post: operations['create_food']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/foods/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch: operations['update_food']
    trace?: never
  }
  '/api/foods/{id}/archive': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['archive_food']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/foods/{id}/unarchive': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['unarchive_food']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['health']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['me']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/meals': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['list_meals']
    put?: never
    post: operations['create_meals']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/meals/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch: operations['update_meal']
    trace?: never
  }
  '/api/meals/{id}/unvoid': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['unvoid_meal']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/meals/{id}/void': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['void_meal']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/tokens': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['list_tokens']
    put?: never
    post: operations['create_token']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/tokens/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete: operations['revoke_token']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/users/{id}/locations': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['list_locations']
    put?: never
    post: operations['create_location']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/users/{id}/locations/{loc_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete: operations['delete_location']
    options?: never
    head?: never
    patch: operations['update_location']
    trace?: never
  }
  '/api/users/{id}/profile': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch: operations['update_profile']
    trace?: never
  }
  '/api/users/{id}/targets': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['list_targets']
    put?: never
    post: operations['create_target']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/users/{id}/targets/{target_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete: operations['delete_target']
    options?: never
    head?: never
    patch: operations['update_target']
    trace?: never
  }
  '/api/weights': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['list_weights']
    put?: never
    post: operations['create_weight']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/weights/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch: operations['update_weight']
    trace?: never
  }
  '/api/weights/{id}/unvoid': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['unvoid_weight']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/weights/{id}/void': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['void_weight']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    ActivityDto: {
      /** Format: int32 */
      created_by: number
      created_via: string
      /** Format: date */
      day: string
      day_override: boolean
      /** @description 45m, 1h, 1h30 */
      duration: string
      /** Format: int32 */
      id: number
      /** Format: int32 */
      kcal?: number | null
      kind: string
      /** Format: int32 */
      minutes: number
      note: string
      /** Format: date-time */
      started_at: string
      timezone: string
      /** Format: int32 */
      user_id: number
      voided: boolean
    }
    ActivityInput: {
      /** Format: date */
      day?: string | null
      /** @description 45, 45m, 1h, 1h30, 1:30 */
      duration: string
      /**
       * Format: int32
       * @description Informational only; never enters the balance
       */
      kcal?: number | null
      /** @description run, gym, cycling, ... */
      kind: string
      note?: string | null
      started_at?: string | null
      timezone?: string | null
      /** Format: int32 */
      user_id?: number | null
    }
    ActivityPatchInput: {
      day?: string | null
      duration?: string | null
      /** Format: int32 */
      kcal?: number | null
      kind?: string | null
      note?: string | null
      started_at?: string | null
      timezone?: string | null
    }
    DayDto: {
      activities: components['schemas']['ActivityDto'][]
      /** Format: int32 */
      balance?: number | null
      /** Format: date */
      day: string
      logged: boolean
      meals: components['schemas']['MealDto'][]
      target?: null | components['schemas']['TargetDto']
      totals: components['schemas']['Totals']
      /** Format: int32 */
      user_id: number
      weights: components['schemas']['WeightDto'][]
    }
    /** @description One calendar day of a range. */
    DayRow: {
      /** Format: int32 */
      balance?: number | null
      /** Format: date */
      day: string
      /** Format: int32 */
      kcal?: number | null
      /** @description At least one meal: unlogged days are gaps, never zeros */
      logged: boolean
      /** Format: int32 */
      meals: number
      /** Format: int32 */
      meals_without_protein: number
      /** Format: int32 */
      protein_g?: number | null
      /** Format: int32 */
      sport_minutes: number
      /** Format: int32 */
      target_kcal?: number | null
      /**
       * Format: int32
       * @description The trend on a day with a reading
       */
      trend_g?: number | null
      /**
       * Format: int32
       * @description The day's first reading, in grams
       */
      weight_g?: number | null
    }
    DaysDto: {
      days: components['schemas']['DayRow'][]
      /** Format: date */
      from: string
      /** Format: date */
      to: string
      /** Format: int32 */
      user_id: number
    }
    ErrorBody: {
      error: components['schemas']['ErrorDetail']
    }
    ErrorDetail: {
      code: string
      message: string
    }
    FoodDto: {
      aliases: string[]
      /** Format: date-time */
      archived_at?: string | null
      /** Format: date-time */
      created_at: string
      /** Format: int32 */
      created_by: number
      /** Format: int32 */
      id: number
      /** Format: int32 */
      kcal: number
      name: string
      portion: string
      /** Format: int32 */
      protein_g?: number | null
      /** Format: date-time */
      updated_at: string
      /**
       * Format: int64
       * @description Non-voided meals logged against it
       */
      uses: number
    }
    FoodInput: {
      aliases?: string[]
      /** Format: int32 */
      kcal: number
      name: string
      /** @description What one portion is: "1 bowl (350 g)" */
      portion: string
      /** Format: int32 */
      protein_g?: number | null
    }
    FoodPatchInput: {
      aliases?: string[] | null
      /** Format: int32 */
      kcal?: number | null
      name?: string | null
      portion?: string | null
      /** Format: int32 */
      protein_g?: number | null
    }
    Health: {
      status: string
    }
    HouseholdDto: {
      /** Format: int32 */
      id: number
      members: components['schemas']['MemberDto'][]
      name: string
    }
    LocationDto: {
      /** Format: int32 */
      id: number
      origin: boolean
      timezone: string
      /** Format: int32 */
      user_id: number
      /**
       * Format: date-time
       * @description RFC 3339, UTC; the origin row is far in the past
       */
      valid_from: string
    }
    LocationInput: {
      timezone: string
      /**
       * Format: date-time
       * @description RFC 3339; default now
       */
      valid_from?: string | null
    }
    LocationPatchInput: {
      timezone?: string | null
      /** Format: date-time */
      valid_from?: string | null
    }
    Me: {
      can_edit: boolean
      can_write: boolean
      household?: null | components['schemas']['HouseholdDto']
      /** @description "session", "token" or "delegate" */
      kind: string
      scopes: string[]
      target?: null | components['schemas']['TargetDto']
      /** @description The zone the user is in right now */
      timezone: string
      /**
       * Format: date
       * @description Today on the user's clock and boundary
       */
      today: string
      user: components['schemas']['UserDto']
    }
    MealDto: {
      /** Format: int32 */
      created_by: number
      created_via: string
      /** Format: date */
      day: string
      day_override: boolean
      description: string
      /** Format: date-time */
      eaten_at: string
      /** Format: int32 */
      food_id?: number | null
      /** Format: int32 */
      id: number
      /** Format: int32 */
      kcal: number
      portions?: string | null
      /** Format: int32 */
      protein_g?: number | null
      source: string
      timezone: string
      /** Format: int32 */
      user_id: number
      voided: boolean
    }
    MealInput: {
      /**
       * Format: date
       * @description Count this meal for this day whatever the clock says
       */
      day?: string | null
      /** @description Required unless a food is given */
      description?: string | null
      /** @description RFC 3339 with an offset, or a wall-clock time (YYYY-MM-DD HH:MM) on the person's current clock; default now */
      eaten_at?: string | null
      /**
       * Format: int32
       * @description A saved food: kcal and protein come from it times `portions`
       */
      food_id?: number | null
      /**
       * Format: int32
       * @description Required unless a food is given
       */
      kcal?: number | null
      /** @description Decimal portion count, default 1 */
      portions?: string | null
      /** Format: int32 */
      protein_g?: number | null
      /** @description estimate (default), manual or label; a food sets it to food */
      source?: string | null
      /** @description IANA zone to compute the day in, instead of the location history */
      timezone?: string | null
      /** @description Whose intake; empty or absent means the caller's. One entry per person. */
      user_ids?: number[]
    }
    MealPatchInput: {
      /** @description Set the accounting day by hand; null goes back to the computed day */
      day?: string | null
      description?: string | null
      eaten_at?: string | null
      /**
       * Format: int32
       * @description Link to a food (its numbers replace the meal's); null unlinks
       */
      food_id?: number | null
      /**
       * Format: int32
       * @description An explicit number unlinks the meal from its food
       */
      kcal?: number | null
      portions?: string | null
      /** Format: int32 */
      protein_g?: number | null
      source?: string | null
      timezone?: string | null
    }
    MemberDto: {
      email?: string | null
      /** Format: int32 */
      id: number
      name?: string | null
    }
    ProfilePatchInput: {
      /** @description Mifflin multiplier, 1.00 to 2.50 */
      activity_factor?: string | null
      born_on?: string | null
      /**
       * Format: int32
       * @description Minutes after midnight the day starts; default 240 (04:00)
       */
      day_boundary_minutes?: number | null
      /** Format: int32 */
      height_mm?: number | null
      name?: string | null
      /** @description female or male, for the Mifflin-St Jeor seed */
      sex?: string | null
    }
    TargetDto: {
      /** Format: int32 */
      id: number
      /** Format: int32 */
      kcal: number
      /** Format: int32 */
      protein_g?: number | null
      /** Format: int32 */
      user_id: number
      /** Format: date */
      valid_from: string
      /** @description Goal weight in kilograms */
      weight_kg?: string | null
    }
    TargetInput: {
      /** Format: int32 */
      kcal: number
      /** Format: int32 */
      protein_g?: number | null
      /**
       * Format: date
       * @description Default today
       */
      valid_from?: string | null
      weight_kg?: string | null
    }
    TargetPatchInput: {
      /** Format: int32 */
      kcal?: number | null
      /** Format: int32 */
      protein_g?: number | null
      /** Format: date */
      valid_from?: string | null
      weight_kg?: string | null
    }
    TokenCreated: {
      /** Format: int32 */
      id: number
      name: string
      scopes: string[]
      /** @description Shown once, never stored */
      secret: string
      /** Format: int32 */
      user_id?: number | null
    }
    TokenDto: {
      /** Format: date-time */
      created_at: string
      /** Format: int32 */
      created_by?: number | null
      /** Format: int32 */
      id: number
      /** Format: date-time */
      last_used_at?: string | null
      name: string
      /** Format: date-time */
      revoked_at?: string | null
      scopes: string[]
      /** Format: int32 */
      user_id?: number | null
    }
    TokenInput: {
      name: string
      /** @description Comma-separated: read, write, edit, delegate */
      scopes: string
      /**
       * Format: int32
       * @description The person a personal token acts as; default the caller. Not for delegate tokens.
       */
      user_id?: number | null
    }
    Totals: {
      /** Format: int32 */
      kcal: number
      /** Format: int32 */
      meals: number
      /** Format: int32 */
      meals_without_protein: number
      /**
       * Format: int32
       * @description Sum over the meals that have protein; null when none do
       */
      protein_g?: number | null
      /** Format: int32 */
      sport_minutes: number
    }
    UserDto: {
      activity_factor: string
      /** Format: date */
      born_on?: string | null
      /** Format: int32 */
      day_boundary_minutes: number
      email?: string | null
      /** Format: int32 */
      height_mm?: number | null
      /** Format: int32 */
      household_id?: number | null
      /** Format: int32 */
      id: number
      name?: string | null
      sex?: string | null
    }
    WeightDto: {
      /** Format: int32 */
      created_by: number
      created_via: string
      /** Format: date */
      day: string
      day_override: boolean
      /** Format: int32 */
      id: number
      /** Format: date-time */
      measured_at: string
      timezone: string
      /** Format: int32 */
      user_id: number
      voided: boolean
      /** Format: int32 */
      weight_g: number
      weight_kg: string
    }
    WeightInput: {
      /** Format: date */
      day?: string | null
      measured_at?: string | null
      timezone?: string | null
      /**
       * Format: int32
       * @description Whose weight; default the caller
       */
      user_id?: number | null
      /** @description Kilograms, e.g. "82.4" */
      weight_kg: string
    }
    WeightPatchInput: {
      day?: string | null
      measured_at?: string | null
      timezone?: string | null
      weight_kg?: string | null
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  list_activities: {
    parameters: {
      query: {
        user?: number | null
        from: string
        to: string
        include_voided?: boolean
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ActivityDto'][]
        }
      }
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  create_activity: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ActivityInput']
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ActivityDto']
        }
      }
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  update_activity: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ActivityPatchInput']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ActivityDto']
        }
      }
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  unvoid_activity: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  void_activity: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  callback: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      302: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description not a member of the required group */
      403: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  login: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description redirect to the identity provider */
      302: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  logout: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  day: {
    parameters: {
      query?: {
        /** @description Whose day; default the caller */
        user?: number | null
        /** @description YYYY-MM-DD; default today on that person's clock */
        date?: string | null
        include_voided?: boolean
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DayDto']
        }
      }
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  days: {
    parameters: {
      query: {
        user?: number | null
        from: string
        to: string
        include_voided?: boolean
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DaysDto']
        }
      }
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  list_foods: {
    parameters: {
      query?: {
        /** @description Fragment of the name or an alias; empty lists everything */
        q?: string | null
        include_archived?: boolean
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['FoodDto'][]
        }
      }
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  create_food: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['FoodInput']
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['FoodDto']
        }
      }
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  update_food: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['FoodPatchInput']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['FoodDto']
        }
      }
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  archive_food: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['FoodDto']
        }
      }
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  unarchive_food: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['FoodDto']
        }
      }
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  health: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Health']
        }
      }
    }
  }
  me: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Me']
        }
      }
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  list_meals: {
    parameters: {
      query: {
        user?: number | null
        from: string
        to: string
        include_voided?: boolean
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MealDto'][]
        }
      }
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  create_meals: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['MealInput']
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MealDto'][]
        }
      }
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  update_meal: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['MealPatchInput']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MealDto']
        }
      }
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  unvoid_meal: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  void_meal: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  list_tokens: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TokenDto'][]
        }
      }
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  create_token: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TokenInput']
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TokenCreated']
        }
      }
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  revoke_token: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  list_locations: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LocationDto'][]
        }
      }
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  create_location: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LocationInput']
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LocationDto']
        }
      }
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  delete_location: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: number
        loc_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  update_location: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: number
        loc_id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LocationPatchInput']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LocationDto']
        }
      }
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  update_profile: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ProfilePatchInput']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserDto']
        }
      }
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  list_targets: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TargetDto'][]
        }
      }
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  create_target: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TargetInput']
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TargetDto']
        }
      }
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  delete_target: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: number
        target_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  update_target: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: number
        target_id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TargetPatchInput']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TargetDto']
        }
      }
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  list_weights: {
    parameters: {
      query: {
        user?: number | null
        from: string
        to: string
        include_voided?: boolean
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WeightDto'][]
        }
      }
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  create_weight: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['WeightInput']
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WeightDto']
        }
      }
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  update_weight: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['WeightPatchInput']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WeightDto']
        }
      }
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  unvoid_weight: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  void_weight: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
}
